// GENERATED by scripts/build-demos.mjs. Do not edit by hand.
// Static imports so every demo is bundled and rendered on its docs page.

import AccordionDemo from './accordion-demo';
import AlertDemo from './alert-demo';
import AlertDestructive from './alert-destructive';
import AlertDialogDemo from './alert-dialog-demo';
import AspectRatioDemo from './aspect-ratio-demo';
import AttachmentDemo from './attachment-demo';
import AvatarDemo from './avatar-demo';
import AvatarSizes from './avatar-sizes';
import BadgeDemo from './badge-demo';
import BadgeTones from './badge-tones';
import BreadcrumbDemo from './breadcrumb-demo';
import BubbleDemo from './bubble-demo';
import ButtonDemo from './button-demo';
import ButtonDestructive from './button-destructive';
import ButtonGroupDemo from './button-group-demo';
import ButtonIcons from './button-icons';
import ButtonSizes from './button-sizes';
import CalendarDemo from './calendar-demo';
import CardDemo from './card-demo';
import CarouselDemo from './carousel-demo';
import ChartDemo from './chart-demo';
import CheckboxDemo from './checkbox-demo';
import CollapsibleDemo from './collapsible-demo';
import ComboboxDemo from './combobox-demo';
import CommandDemo from './command-demo';
import ContextMenuDemo from './context-menu-demo';
import DialogDemo from './dialog-demo';
import DirectionDemo from './direction-demo';
import DrawerDemo from './drawer-demo';
import DropdownMenuDemo from './dropdown-menu-demo';
import EmptyDemo from './empty-demo';
import FieldDemo from './field-demo';
import HoverCardDemo from './hover-card-demo';
import InputDemo from './input-demo';
import InputGroupDemo from './input-group-demo';
import InputOtpDemo from './input-otp-demo';
import ItemDemo from './item-demo';
import KbdDemo from './kbd-demo';
import LabelDemo from './label-demo';
import MarkerDemo from './marker-demo';
import MenubarDemo from './menubar-demo';
import MessageDemo from './message-demo';
import MessageScrollerDemo from './message-scroller-demo';
import NativeSelectDemo from './native-select-demo';
import NavigationMenuDemo from './navigation-menu-demo';
import PaginationDemo from './pagination-demo';
import PopoverDemo from './popover-demo';
import ProgressDemo from './progress-demo';
import QuestionnaireDemo from './questionnaire-demo';
import RadioGroupDemo from './radio-group-demo';
import ResizableDemo from './resizable-demo';
import ScrollAreaDemo from './scroll-area-demo';
import SelectDemo from './select-demo';
import SeparatorDemo from './separator-demo';
import SheetDemo from './sheet-demo';
import SkeletonDemo from './skeleton-demo';
import SliderDemo from './slider-demo';
import SonnerDemo from './sonner-demo';
import SpinnerDemo from './spinner-demo';
import SwitchDemo from './switch-demo';
import TableDemo from './table-demo';
import TabsDemo from './tabs-demo';
import TabsLine from './tabs-line';
import TextareaDemo from './textarea-demo';
import ToggleDemo from './toggle-demo';
import ToggleGroupDemo from './toggle-group-demo';
import TooltipDemo from './tooltip-demo';

export const demos = {
  'accordion-demo': AccordionDemo,
  'alert-demo': AlertDemo,
  'alert-destructive': AlertDestructive,
  'alert-dialog-demo': AlertDialogDemo,
  'aspect-ratio-demo': AspectRatioDemo,
  'attachment-demo': AttachmentDemo,
  'avatar-demo': AvatarDemo,
  'avatar-sizes': AvatarSizes,
  'badge-demo': BadgeDemo,
  'badge-tones': BadgeTones,
  'breadcrumb-demo': BreadcrumbDemo,
  'bubble-demo': BubbleDemo,
  'button-demo': ButtonDemo,
  'button-destructive': ButtonDestructive,
  'button-group-demo': ButtonGroupDemo,
  'button-icons': ButtonIcons,
  'button-sizes': ButtonSizes,
  'calendar-demo': CalendarDemo,
  'card-demo': CardDemo,
  'carousel-demo': CarouselDemo,
  'chart-demo': ChartDemo,
  'checkbox-demo': CheckboxDemo,
  'collapsible-demo': CollapsibleDemo,
  'combobox-demo': ComboboxDemo,
  'command-demo': CommandDemo,
  'context-menu-demo': ContextMenuDemo,
  'dialog-demo': DialogDemo,
  'direction-demo': DirectionDemo,
  'drawer-demo': DrawerDemo,
  'dropdown-menu-demo': DropdownMenuDemo,
  'empty-demo': EmptyDemo,
  'field-demo': FieldDemo,
  'hover-card-demo': HoverCardDemo,
  'input-demo': InputDemo,
  'input-group-demo': InputGroupDemo,
  'input-otp-demo': InputOtpDemo,
  'item-demo': ItemDemo,
  'kbd-demo': KbdDemo,
  'label-demo': LabelDemo,
  'marker-demo': MarkerDemo,
  'menubar-demo': MenubarDemo,
  'message-demo': MessageDemo,
  'message-scroller-demo': MessageScrollerDemo,
  'native-select-demo': NativeSelectDemo,
  'navigation-menu-demo': NavigationMenuDemo,
  'pagination-demo': PaginationDemo,
  'popover-demo': PopoverDemo,
  'progress-demo': ProgressDemo,
  'questionnaire-demo': QuestionnaireDemo,
  'radio-group-demo': RadioGroupDemo,
  'resizable-demo': ResizableDemo,
  'scroll-area-demo': ScrollAreaDemo,
  'select-demo': SelectDemo,
  'separator-demo': SeparatorDemo,
  'sheet-demo': SheetDemo,
  'skeleton-demo': SkeletonDemo,
  'slider-demo': SliderDemo,
  'sonner-demo': SonnerDemo,
  'spinner-demo': SpinnerDemo,
  'switch-demo': SwitchDemo,
  'table-demo': TableDemo,
  'tabs-demo': TabsDemo,
  'tabs-line': TabsLine,
  'textarea-demo': TextareaDemo,
  'toggle-demo': ToggleDemo,
  'toggle-group-demo': ToggleGroupDemo,
  'tooltip-demo': TooltipDemo,
} as const

export type DemoName = keyof typeof demos
