// Generates src/styles/tokens.css and src/tokens.ts from tokens/nooxit.tokens.json.
// Run with `pnpm --filter nooxit-design-system tokens` after editing the JSON.
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const source = JSON.parse(
  readFileSync(resolve(root, "tokens/nooxit.tokens.json"), "utf8")
)

const HEADER =
  "GENERATED by scripts/build-tokens.mjs from tokens/nooxit.tokens.json. Do not edit by hand."

// Primitives are addressed as "<family>-<step>" (e.g. "gray-200", "base-white").
const primitives = []
for (const [family, steps] of Object.entries(source.primitives)) {
  for (const [step, hex] of Object.entries(steps)) {
    primitives.push({ family, step, name: `${family}-${step}`, hex })
  }
}
const primitiveHex = Object.fromEntries(primitives.map((p) => [p.name, p.hex]))

function normalizeValue(value) {
  const ref = typeof value === "string" ? value : value.ref
  const alpha = typeof value === "string" ? undefined : value.alpha
  if (!(ref in primitiveHex)) {
    throw new Error(`Unknown primitive "${ref}"`)
  }
  return { ref, alpha }
}

function cssValue({ ref, alpha }) {
  return alpha === undefined
    ? `var(--${ref})`
    : `color-mix(in srgb, var(--${ref}) ${alpha}%, transparent)`
}

function resolvedHex({ ref, alpha }) {
  const hex = primitiveHex[ref]
  if (alpha === undefined) return hex
  const a = Math.round((alpha / 100) * 255)
    .toString(16)
    .padStart(2, "0")
  return `${hex}${a}`
}

const semantic = source.semantic.map((token) => {
  const light = normalizeValue(token.light)
  const dark = normalizeValue(token.dark)
  const tw = token.tailwind ?? {}
  // Tailwind utility names this token is reachable through.
  const utilities = []
  const themeVars = []
  if (tw.namespace) {
    themeVars.push(`--${tw.namespace}-${tw.key}`)
    const prefix = tw.namespace === "background-color" ? "bg" : "border"
    utilities.push(`${prefix}-${tw.key}`)
  } else {
    themeVars.push(`--color-${token.name}`)
    utilities.push(`bg-${token.name}`, `text-${token.name}`, `border-${token.name}`)
  }
  for (const alias of tw.aliases ?? []) {
    themeVars.push(`--color-${alias}`)
    utilities.push(`bg-${alias}`)
  }
  return { ...token, light, dark, themeVars, utilities }
})

// ---------------------------------------------------------------------------
// tokens.css
// ---------------------------------------------------------------------------
const css = []
css.push(`/* ${HEADER} */`, "")
css.push("/* Primitives (Figma collection: colors_primitives). */")
css.push(":root {")
let lastFamily = null
for (const p of primitives) {
  if (lastFamily && lastFamily !== p.family) css.push("")
  css.push(`  --${p.name}: ${p.hex};`)
  lastFamily = p.family
}
css.push("}", "")

for (const mode of ["light", "dark"]) {
  css.push(
    mode === "light"
      ? "/* Semantic tokens, light mode (Figma collection: color_tokens / light). */"
      : "/* Semantic tokens, dark mode (Figma collection: color_tokens / dark). */"
  )
  css.push(mode === "light" ? ":root {" : ".dark {")
  let lastGroup = null
  for (const t of semantic) {
    if (t.group !== lastGroup) {
      if (lastGroup) css.push("")
      css.push(`  /* ${t.group} */`)
      lastGroup = t.group
    }
    const note = t.origin ? ` /* ${t.origin}: not a Figma variable */` : ""
    css.push(`  --${t.name}: ${cssValue(t[mode])};${note}`)
  }
  // Declared in both modes so a nested .dark wrapper re-resolves it.
  css.push("", "  /* Aliases kept for shadcn/ui compatibility */")
  css.push("  --sidebar: var(--sidebar-background);")
  css.push("}", "")
}

css.push("/* Remove Tailwind's default palette: only Nooxit colors exist. */")
css.push("@theme {", "  --color-*: initial;", "}", "")
css.push("@theme inline {")
css.push("  /* Primitives: bg-gray-200, text-orange-950, ... */")
for (const p of primitives) css.push(`  --color-${p.name}: var(--${p.name});`)
css.push("")
css.push("  /* Semantic tokens: bg-primary, text-muted-foreground, bg-muted-40, ... */")
for (const t of semantic) {
  for (const v of t.themeVars) css.push(`  ${v}: var(--${t.name});`)
}
css.push("}", "")
writeFileSync(resolve(root, "src/styles/tokens.css"), css.join("\n"))

// ---------------------------------------------------------------------------
// tokens.ts
// ---------------------------------------------------------------------------
const ts = []
ts.push(`// ${HEADER}`, "")
ts.push("export type TokenValue = {")
ts.push("  /** Primitive the token points to, e.g. \"gray-200\". */")
ts.push("  ref: string")
ts.push("  /** Opacity in percent when the token is a translucent primitive. */")
ts.push("  alpha?: number")
ts.push("  /** Resolved hex value (#rrggbb or #rrggbbaa). */")
ts.push("  hex: string")
ts.push("}", "")
ts.push("export type SemanticToken = {")
ts.push("  name: string")
ts.push("  group: string")
ts.push("  /** CSS custom property, e.g. \"--primary\". */")
ts.push("  cssVar: string")
ts.push("  /** Figma variable path, or null when the token is not in Figma. */")
ts.push("  figma: string | null")
ts.push("  origin?: \"added\" | \"proposed\"")
ts.push("  /** Example Tailwind utilities that use the token. */")
ts.push("  utilities: string[]")
ts.push("  light: TokenValue")
ts.push("  dark: TokenValue")
ts.push("  description: string")
ts.push("}", "")
ts.push("export type Primitive = { family: string; step: string; name: string; cssVar: string; hex: string }", "")

const primitiveOut = primitives.map((p) => ({
  family: p.family,
  step: p.step,
  name: p.name,
  cssVar: `--${p.name}`,
  hex: p.hex,
}))
ts.push(
  `export const primitives: Primitive[] = ${JSON.stringify(primitiveOut, null, 2)}`,
  ""
)
const semanticOut = semantic.map((t) => ({
  name: t.name,
  group: t.group,
  cssVar: `--${t.name}`,
  figma: t.figma,
  ...(t.origin ? { origin: t.origin } : {}),
  utilities: t.utilities,
  light: { ...t.light, hex: resolvedHex(t.light) },
  dark: { ...t.dark, hex: resolvedHex(t.dark) },
  description: t.description,
}))
ts.push(
  `export const semanticTokens: SemanticToken[] = ${JSON.stringify(semanticOut, null, 2)}`,
  ""
)
writeFileSync(resolve(root, "src/tokens.ts"), ts.join("\n"))

console.log(
  `tokens: ${primitives.length} primitives, ${semantic.length} semantic tokens -> src/styles/tokens.css, src/tokens.ts`
)
