// GENERATED by scripts/build-tokens.mjs from tokens/nooxit.tokens.json. Do not edit by hand.

export type TokenValue = {
  /** Primitive the token points to, e.g. "gray-200". */
  ref: string
  /** Opacity in percent when the token is a translucent primitive. */
  alpha?: number
  /** Resolved hex value (#rrggbb or #rrggbbaa). */
  hex: string
}

export type SemanticToken = {
  name: string
  group: string
  /** CSS custom property, e.g. "--primary". */
  cssVar: string
  /** Figma variable path, or null when the token is not in Figma. */
  figma: string | null
  /** added/proposed: not a Figma variable. adjusted: in Figma, but the value was corrected. */
  origin?: "added" | "proposed" | "adjusted"
  /** The Figma value when origin is "adjusted". */
  figmaValue?: { light: string; dark: string }
  /** Example Tailwind utilities that use the token. */
  utilities: string[]
  light: TokenValue
  dark: TokenValue
  description: string
}

export type Primitive = { family: string; step: string; name: string; cssVar: string; hex: string }

export const primitives: Primitive[] = [
  {
    "family": "base",
    "step": "black",
    "name": "base-black",
    "cssVar": "--base-black",
    "hex": "#110f0e"
  },
  {
    "family": "base",
    "step": "white",
    "name": "base-white",
    "cssVar": "--base-white",
    "hex": "#fbfaf9"
  },
  {
    "family": "gray",
    "step": "50",
    "name": "gray-50",
    "cssVar": "--gray-50",
    "hex": "#f4f2f0"
  },
  {
    "family": "gray",
    "step": "100",
    "name": "gray-100",
    "cssVar": "--gray-100",
    "hex": "#efedeb"
  },
  {
    "family": "gray",
    "step": "200",
    "name": "gray-200",
    "cssVar": "--gray-200",
    "hex": "#e0dedc"
  },
  {
    "family": "gray",
    "step": "300",
    "name": "gray-300",
    "cssVar": "--gray-300",
    "hex": "#cdcbc9"
  },
  {
    "family": "gray",
    "step": "400",
    "name": "gray-400",
    "cssVar": "--gray-400",
    "hex": "#b7b5b3"
  },
  {
    "family": "gray",
    "step": "500",
    "name": "gray-500",
    "cssVar": "--gray-500",
    "hex": "#999795"
  },
  {
    "family": "gray",
    "step": "600",
    "name": "gray-600",
    "cssVar": "--gray-600",
    "hex": "#7f7d7b"
  },
  {
    "family": "gray",
    "step": "700",
    "name": "gray-700",
    "cssVar": "--gray-700",
    "hex": "#676563"
  },
  {
    "family": "gray",
    "step": "800",
    "name": "gray-800",
    "cssVar": "--gray-800",
    "hex": "#494745"
  },
  {
    "family": "gray",
    "step": "900",
    "name": "gray-900",
    "cssVar": "--gray-900",
    "hex": "#32302e"
  },
  {
    "family": "gray",
    "step": "950",
    "name": "gray-950",
    "cssVar": "--gray-950",
    "hex": "#1c1b1a"
  },
  {
    "family": "orange",
    "step": "50",
    "name": "orange-50",
    "cssVar": "--orange-50",
    "hex": "#fff2ee"
  },
  {
    "family": "orange",
    "step": "100",
    "name": "orange-100",
    "cssVar": "--orange-100",
    "hex": "#fee7df"
  },
  {
    "family": "orange",
    "step": "200",
    "name": "orange-200",
    "cssVar": "--orange-200",
    "hex": "#fed1c2"
  },
  {
    "family": "orange",
    "step": "300",
    "name": "orange-300",
    "cssVar": "--orange-300",
    "hex": "#feb49b"
  },
  {
    "family": "orange",
    "step": "400",
    "name": "orange-400",
    "cssVar": "--orange-400",
    "hex": "#fd8a62"
  },
  {
    "family": "orange",
    "step": "500",
    "name": "orange-500",
    "cssVar": "--orange-500",
    "hex": "#ff5900"
  },
  {
    "family": "orange",
    "step": "600",
    "name": "orange-600",
    "cssVar": "--orange-600",
    "hex": "#d24b0d"
  },
  {
    "family": "orange",
    "step": "700",
    "name": "orange-700",
    "cssVar": "--orange-700",
    "hex": "#ab3c08"
  },
  {
    "family": "orange",
    "step": "800",
    "name": "orange-800",
    "cssVar": "--orange-800",
    "hex": "#872d05"
  },
  {
    "family": "orange",
    "step": "900",
    "name": "orange-900",
    "cssVar": "--orange-900",
    "hex": "#662003"
  },
  {
    "family": "orange",
    "step": "950",
    "name": "orange-950",
    "cssVar": "--orange-950",
    "hex": "#4e1601"
  },
  {
    "family": "red",
    "step": "50",
    "name": "red-50",
    "cssVar": "--red-50",
    "hex": "#fff5f4"
  },
  {
    "family": "red",
    "step": "100",
    "name": "red-100",
    "cssVar": "--red-100",
    "hex": "#fee6e4"
  },
  {
    "family": "red",
    "step": "200",
    "name": "red-200",
    "cssVar": "--red-200",
    "hex": "#fecfcb"
  },
  {
    "family": "red",
    "step": "300",
    "name": "red-300",
    "cssVar": "--red-300",
    "hex": "#feb0aa"
  },
  {
    "family": "red",
    "step": "400",
    "name": "red-400",
    "cssVar": "--red-400",
    "hex": "#fd837d"
  },
  {
    "family": "red",
    "step": "500",
    "name": "red-500",
    "cssVar": "--red-500",
    "hex": "#ee5c5a"
  },
  {
    "family": "red",
    "step": "600",
    "name": "red-600",
    "cssVar": "--red-600",
    "hex": "#d24142"
  },
  {
    "family": "red",
    "step": "700",
    "name": "red-700",
    "cssVar": "--red-700",
    "hex": "#b22a2f"
  },
  {
    "family": "red",
    "step": "800",
    "name": "red-800",
    "cssVar": "--red-800",
    "hex": "#91171f"
  },
  {
    "family": "red",
    "step": "900",
    "name": "red-900",
    "cssVar": "--red-900",
    "hex": "#710913"
  },
  {
    "family": "red",
    "step": "950",
    "name": "red-950",
    "cssVar": "--red-950",
    "hex": "#4e0309"
  },
  {
    "family": "yellow",
    "step": "50",
    "name": "yellow-50",
    "cssVar": "--yellow-50",
    "hex": "#fdfbd7"
  },
  {
    "family": "yellow",
    "step": "100",
    "name": "yellow-100",
    "cssVar": "--yellow-100",
    "hex": "#f6f2af"
  },
  {
    "family": "yellow",
    "step": "200",
    "name": "yellow-200",
    "cssVar": "--yellow-200",
    "hex": "#f4e409"
  },
  {
    "family": "yellow",
    "step": "300",
    "name": "yellow-300",
    "cssVar": "--yellow-300",
    "hex": "#dbcd1d"
  },
  {
    "family": "yellow",
    "step": "400",
    "name": "yellow-400",
    "cssVar": "--yellow-400",
    "hex": "#bdb118"
  },
  {
    "family": "yellow",
    "step": "500",
    "name": "yellow-500",
    "cssVar": "--yellow-500",
    "hex": "#a29713"
  },
  {
    "family": "yellow",
    "step": "600",
    "name": "yellow-600",
    "cssVar": "--yellow-600",
    "hex": "#887f0e"
  },
  {
    "family": "yellow",
    "step": "700",
    "name": "yellow-700",
    "cssVar": "--yellow-700",
    "hex": "#6f6709"
  },
  {
    "family": "yellow",
    "step": "800",
    "name": "yellow-800",
    "cssVar": "--yellow-800",
    "hex": "#565005"
  },
  {
    "family": "yellow",
    "step": "900",
    "name": "yellow-900",
    "cssVar": "--yellow-900",
    "hex": "#413c03"
  },
  {
    "family": "yellow",
    "step": "950",
    "name": "yellow-950",
    "cssVar": "--yellow-950",
    "hex": "#302c07"
  },
  {
    "family": "lime",
    "step": "50",
    "name": "lime-50",
    "cssVar": "--lime-50",
    "hex": "#eeffca"
  },
  {
    "family": "lime",
    "step": "100",
    "name": "lime-100",
    "cssVar": "--lime-100",
    "hex": "#d2ff28"
  },
  {
    "family": "lime",
    "step": "200",
    "name": "lime-200",
    "cssVar": "--lime-200",
    "hex": "#c5ef21"
  },
  {
    "family": "lime",
    "step": "300",
    "name": "lime-300",
    "cssVar": "--lime-300",
    "hex": "#b2d91d"
  },
  {
    "family": "lime",
    "step": "400",
    "name": "lime-400",
    "cssVar": "--lime-400",
    "hex": "#9abc18"
  },
  {
    "family": "lime",
    "step": "500",
    "name": "lime-500",
    "cssVar": "--lime-500",
    "hex": "#84a213"
  },
  {
    "family": "lime",
    "step": "600",
    "name": "lime-600",
    "cssVar": "--lime-600",
    "hex": "#6e880e"
  },
  {
    "family": "lime",
    "step": "700",
    "name": "lime-700",
    "cssVar": "--lime-700",
    "hex": "#5a6e09"
  },
  {
    "family": "lime",
    "step": "800",
    "name": "lime-800",
    "cssVar": "--lime-800",
    "hex": "#455605"
  },
  {
    "family": "lime",
    "step": "900",
    "name": "lime-900",
    "cssVar": "--lime-900",
    "hex": "#334103"
  },
  {
    "family": "lime",
    "step": "950",
    "name": "lime-950",
    "cssVar": "--lime-950",
    "hex": "#212b01"
  },
  {
    "family": "green",
    "step": "50",
    "name": "green-50",
    "cssVar": "--green-50",
    "hex": "#e7fbee"
  },
  {
    "family": "green",
    "step": "100",
    "name": "green-100",
    "cssVar": "--green-100",
    "hex": "#dcf4e4"
  },
  {
    "family": "green",
    "step": "200",
    "name": "green-200",
    "cssVar": "--green-200",
    "hex": "#bce9cc"
  },
  {
    "family": "green",
    "step": "300",
    "name": "green-300",
    "cssVar": "--green-300",
    "hex": "#95dab0"
  },
  {
    "family": "green",
    "step": "400",
    "name": "green-400",
    "cssVar": "--green-400",
    "hex": "#6cc290"
  },
  {
    "family": "green",
    "step": "500",
    "name": "green-500",
    "cssVar": "--green-500",
    "hex": "#49aa75"
  },
  {
    "family": "green",
    "step": "600",
    "name": "green-600",
    "cssVar": "--green-600",
    "hex": "#2d915e"
  },
  {
    "family": "green",
    "step": "700",
    "name": "green-700",
    "cssVar": "--green-700",
    "hex": "#13794a"
  },
  {
    "family": "green",
    "step": "800",
    "name": "green-800",
    "cssVar": "--green-800",
    "hex": "#07623a"
  },
  {
    "family": "green",
    "step": "900",
    "name": "green-900",
    "cssVar": "--green-900",
    "hex": "#004f2d"
  },
  {
    "family": "green",
    "step": "950",
    "name": "green-950",
    "cssVar": "--green-950",
    "hex": "#02321b"
  },
  {
    "family": "blue",
    "step": "50",
    "name": "blue-50",
    "cssVar": "--blue-50",
    "hex": "#f4f8ff"
  },
  {
    "family": "blue",
    "step": "100",
    "name": "blue-100",
    "cssVar": "--blue-100",
    "hex": "#e4edfe"
  },
  {
    "family": "blue",
    "step": "200",
    "name": "blue-200",
    "cssVar": "--blue-200",
    "hex": "#ccddfe"
  },
  {
    "family": "blue",
    "step": "300",
    "name": "blue-300",
    "cssVar": "--blue-300",
    "hex": "#adc7fd"
  },
  {
    "family": "blue",
    "step": "400",
    "name": "blue-400",
    "cssVar": "--blue-400",
    "hex": "#84aafd"
  },
  {
    "family": "blue",
    "step": "500",
    "name": "blue-500",
    "cssVar": "--blue-500",
    "hex": "#5e8dfc"
  },
  {
    "family": "blue",
    "step": "600",
    "name": "blue-600",
    "cssVar": "--blue-600",
    "hex": "#376cfb"
  },
  {
    "family": "blue",
    "step": "700",
    "name": "blue-700",
    "cssVar": "--blue-700",
    "hex": "#1344f5"
  },
  {
    "family": "blue",
    "step": "800",
    "name": "blue-800",
    "cssVar": "--blue-800",
    "hex": "#072ac8"
  },
  {
    "family": "blue",
    "step": "900",
    "name": "blue-900",
    "cssVar": "--blue-900",
    "hex": "#041ca0"
  },
  {
    "family": "blue",
    "step": "950",
    "name": "blue-950",
    "cssVar": "--blue-950",
    "hex": "#021072"
  }
]

export const semanticTokens: SemanticToken[] = [
  {
    "name": "background",
    "group": "Base",
    "cssVar": "--background",
    "figma": "background/main",
    "utilities": [
      "bg-background",
      "text-background",
      "border-background"
    ],
    "light": {
      "ref": "base-white",
      "hex": "#fbfaf9"
    },
    "dark": {
      "ref": "base-black",
      "hex": "#110f0e"
    },
    "description": "Default background of the page (<body />) and base surfaces."
  },
  {
    "name": "foreground",
    "group": "Base",
    "cssVar": "--foreground",
    "figma": "foreground/main",
    "utilities": [
      "bg-foreground",
      "text-foreground",
      "border-foreground"
    ],
    "light": {
      "ref": "base-black",
      "hex": "#110f0e"
    },
    "dark": {
      "ref": "base-white",
      "hex": "#fbfaf9"
    },
    "description": "Default text color on background."
  },
  {
    "name": "card",
    "group": "Surfaces",
    "cssVar": "--card",
    "figma": "background/card",
    "utilities": [
      "bg-card",
      "text-card",
      "border-card"
    ],
    "light": {
      "ref": "base-white",
      "hex": "#fbfaf9"
    },
    "dark": {
      "ref": "base-black",
      "hex": "#110f0e"
    },
    "description": "Background for <Card />."
  },
  {
    "name": "card-foreground",
    "group": "Surfaces",
    "cssVar": "--card-foreground",
    "figma": "foreground/card",
    "utilities": [
      "bg-card-foreground",
      "text-card-foreground",
      "border-card-foreground"
    ],
    "light": {
      "ref": "base-black",
      "hex": "#110f0e"
    },
    "dark": {
      "ref": "base-white",
      "hex": "#fbfaf9"
    },
    "description": "Text color on cards."
  },
  {
    "name": "popover",
    "group": "Surfaces",
    "cssVar": "--popover",
    "figma": "background/popover",
    "utilities": [
      "bg-popover",
      "text-popover",
      "border-popover"
    ],
    "light": {
      "ref": "base-white",
      "hex": "#fbfaf9"
    },
    "dark": {
      "ref": "base-black",
      "hex": "#110f0e"
    },
    "description": "Background for popovers such as <DropdownMenu />, <HoverCard />, <Popover />."
  },
  {
    "name": "popover-foreground",
    "group": "Surfaces",
    "cssVar": "--popover-foreground",
    "figma": "foreground/popover",
    "utilities": [
      "bg-popover-foreground",
      "text-popover-foreground",
      "border-popover-foreground"
    ],
    "light": {
      "ref": "base-black",
      "hex": "#110f0e"
    },
    "dark": {
      "ref": "base-white",
      "hex": "#fbfaf9"
    },
    "description": "Text color in popovers."
  },
  {
    "name": "primary",
    "group": "Primary",
    "cssVar": "--primary",
    "figma": "background/primary",
    "utilities": [
      "bg-primary",
      "text-primary",
      "border-primary"
    ],
    "light": {
      "ref": "base-black",
      "hex": "#110f0e"
    },
    "dark": {
      "ref": "base-white",
      "hex": "#fbfaf9"
    },
    "description": "Primary color, e.g. the default <Button />."
  },
  {
    "name": "primary-foreground",
    "group": "Primary",
    "cssVar": "--primary-foreground",
    "figma": "foreground/primary",
    "utilities": [
      "bg-primary-foreground",
      "text-primary-foreground",
      "border-primary-foreground"
    ],
    "light": {
      "ref": "base-white",
      "hex": "#fbfaf9"
    },
    "dark": {
      "ref": "base-black",
      "hex": "#110f0e"
    },
    "description": "Text and icons on primary."
  },
  {
    "name": "hover-primary",
    "group": "Primary",
    "cssVar": "--hover-primary",
    "figma": "background/hover:primary",
    "origin": "adjusted",
    "figmaValue": {
      "light": "gray-900",
      "dark": "gray-100"
    },
    "utilities": [
      "bg-hover-primary",
      "text-hover-primary",
      "border-hover-primary"
    ],
    "light": {
      "ref": "gray-800",
      "hex": "#494745"
    },
    "dark": {
      "ref": "gray-200",
      "hex": "#e0dedc"
    },
    "description": "Primary background on hover."
  },
  {
    "name": "secondary",
    "group": "Secondary",
    "cssVar": "--secondary",
    "figma": "background/secondary",
    "utilities": [
      "bg-secondary",
      "text-secondary",
      "border-secondary"
    ],
    "light": {
      "ref": "gray-100",
      "hex": "#efedeb"
    },
    "dark": {
      "ref": "gray-950",
      "hex": "#1c1b1a"
    },
    "description": "Secondary color, e.g. <Button variant=\"secondary\" />."
  },
  {
    "name": "secondary-foreground",
    "group": "Secondary",
    "cssVar": "--secondary-foreground",
    "figma": "foreground/secondary",
    "utilities": [
      "bg-secondary-foreground",
      "text-secondary-foreground",
      "border-secondary-foreground"
    ],
    "light": {
      "ref": "base-black",
      "hex": "#110f0e"
    },
    "dark": {
      "ref": "base-white",
      "hex": "#fbfaf9"
    },
    "description": "Text and icons on secondary."
  },
  {
    "name": "hover-secondary",
    "group": "Secondary",
    "cssVar": "--hover-secondary",
    "figma": "background/hover:secondary",
    "utilities": [
      "bg-hover-secondary",
      "text-hover-secondary",
      "border-hover-secondary"
    ],
    "light": {
      "ref": "gray-200",
      "hex": "#e0dedc"
    },
    "dark": {
      "ref": "gray-800",
      "hex": "#494745"
    },
    "description": "Secondary, outline and ghost backgrounds on hover."
  },
  {
    "name": "muted",
    "group": "Muted",
    "cssVar": "--muted",
    "figma": "background/muted",
    "utilities": [
      "bg-muted",
      "text-muted",
      "border-muted"
    ],
    "light": {
      "ref": "gray-50",
      "hex": "#f4f2f0"
    },
    "dark": {
      "ref": "gray-950",
      "hex": "#1c1b1a"
    },
    "description": "Muted backgrounds such as <TabsList />, <Skeleton /> and <Switch />."
  },
  {
    "name": "muted-foreground",
    "group": "Muted",
    "cssVar": "--muted-foreground",
    "figma": "foreground/muted",
    "utilities": [
      "bg-muted-foreground",
      "text-muted-foreground",
      "border-muted-foreground"
    ],
    "light": {
      "ref": "gray-600",
      "hex": "#7f7d7b"
    },
    "dark": {
      "ref": "gray-400",
      "hex": "#b7b5b3"
    },
    "description": "Secondary text: descriptions, placeholders, captions."
  },
  {
    "name": "bg-muted-40",
    "group": "Muted",
    "cssVar": "--bg-muted-40",
    "figma": "background/bg-muted-40",
    "origin": "adjusted",
    "figmaValue": {
      "light": "base-white@40",
      "dark": "base-black@40"
    },
    "utilities": [
      "bg-muted-40"
    ],
    "light": {
      "ref": "gray-50",
      "alpha": 40,
      "hex": "#f4f2f066"
    },
    "dark": {
      "ref": "gray-950",
      "alpha": 40,
      "hex": "#1c1b1a66"
    },
    "description": "Translucent muted surface (muted at 40%). Figma stores base-white/base-black at 40%, which is invisible on the page background; the value follows the Figma code syntax (muted/.4) instead."
  },
  {
    "name": "bg-muted-50",
    "group": "Muted",
    "cssVar": "--bg-muted-50",
    "figma": "background/bg-muted-50",
    "origin": "adjusted",
    "figmaValue": {
      "light": "base-white@50",
      "dark": "base-black@50"
    },
    "utilities": [
      "bg-muted-50"
    ],
    "light": {
      "ref": "gray-50",
      "alpha": 50,
      "hex": "#f4f2f080"
    },
    "dark": {
      "ref": "gray-950",
      "alpha": 50,
      "hex": "#1c1b1a80"
    },
    "description": "Translucent muted surface (muted at 50%), e.g. table row hover and table footer. Figma stores base-white/base-black at 50%, which is invisible on the page background; the value follows the Figma code syntax (muted/.5) instead."
  },
  {
    "name": "accent",
    "group": "Accent",
    "cssVar": "--accent",
    "figma": "background/accent",
    "utilities": [
      "bg-accent",
      "text-accent",
      "border-accent"
    ],
    "light": {
      "ref": "orange-100",
      "hex": "#fee7df"
    },
    "dark": {
      "ref": "orange-950",
      "hex": "#4e1601"
    },
    "description": "Accent surface for hover and active states on menu items, select items, etc."
  },
  {
    "name": "accent-foreground",
    "group": "Accent",
    "cssVar": "--accent-foreground",
    "figma": "foreground/accent",
    "utilities": [
      "bg-accent-foreground",
      "text-accent-foreground",
      "border-accent-foreground"
    ],
    "light": {
      "ref": "orange-950",
      "hex": "#4e1601"
    },
    "dark": {
      "ref": "orange-100",
      "hex": "#fee7df"
    },
    "description": "Text and icons on accent."
  },
  {
    "name": "bg-accent-50",
    "group": "Accent",
    "cssVar": "--bg-accent-50",
    "figma": "background/bg-accent-50",
    "origin": "adjusted",
    "figmaValue": {
      "light": "base-white@50",
      "dark": "base-black@50"
    },
    "utilities": [
      "bg-accent-50"
    ],
    "light": {
      "ref": "orange-100",
      "alpha": 50,
      "hex": "#fee7df80"
    },
    "dark": {
      "ref": "orange-950",
      "alpha": 50,
      "hex": "#4e160180"
    },
    "description": "Translucent accent surface (accent at 50%), e.g. an open <NavigationMenuTrigger />. Figma stores base-white/base-black at 50%; the value follows the Figma code syntax (accent/.5) instead."
  },
  {
    "name": "destructive",
    "group": "Destructive",
    "cssVar": "--destructive",
    "figma": "background/destructive",
    "utilities": [
      "bg-destructive",
      "text-destructive",
      "border-destructive"
    ],
    "light": {
      "ref": "red-600",
      "hex": "#d24142"
    },
    "dark": {
      "ref": "red-500",
      "hex": "#ee5c5a"
    },
    "description": "Destructive actions, e.g. <Button destructive />."
  },
  {
    "name": "destructive-foreground",
    "group": "Destructive",
    "cssVar": "--destructive-foreground",
    "figma": "foreground/destructive",
    "utilities": [
      "bg-destructive-foreground",
      "text-destructive-foreground",
      "border-destructive-foreground"
    ],
    "light": {
      "ref": "red-50",
      "hex": "#fff5f4"
    },
    "dark": {
      "ref": "red-950",
      "hex": "#4e0309"
    },
    "description": "Text and icons on destructive."
  },
  {
    "name": "hover-destructive",
    "group": "Destructive",
    "cssVar": "--hover-destructive",
    "figma": "background/hover:destructive",
    "origin": "adjusted",
    "figmaValue": {
      "light": "red-500",
      "dark": "red-800"
    },
    "utilities": [
      "bg-hover-destructive",
      "text-hover-destructive",
      "border-hover-destructive"
    ],
    "light": {
      "ref": "red-400",
      "hex": "#fd837d"
    },
    "dark": {
      "ref": "red-400",
      "hex": "#fd837d"
    },
    "description": "Destructive background on hover."
  },
  {
    "name": "destructive-muted",
    "group": "Destructive",
    "cssVar": "--destructive-muted",
    "figma": "background/destructive-muted",
    "utilities": [
      "bg-destructive-muted",
      "text-destructive-muted",
      "border-destructive-muted"
    ],
    "light": {
      "ref": "red-100",
      "hex": "#fee6e4"
    },
    "dark": {
      "ref": "red-950",
      "hex": "#4e0309"
    },
    "description": "Subtle destructive surface."
  },
  {
    "name": "destructive-muted-foreground",
    "group": "Destructive",
    "cssVar": "--destructive-muted-foreground",
    "figma": "foreground/destructive-muted",
    "utilities": [
      "bg-destructive-muted-foreground",
      "text-destructive-muted-foreground",
      "border-destructive-muted-foreground"
    ],
    "light": {
      "ref": "red-950",
      "hex": "#4e0309"
    },
    "dark": {
      "ref": "red-100",
      "hex": "#fee6e4"
    },
    "description": "Destructive text on neutral or muted surfaces."
  },
  {
    "name": "bg-destructive-10",
    "group": "Destructive",
    "cssVar": "--bg-destructive-10",
    "figma": "background/bg-destructive-10",
    "origin": "adjusted",
    "figmaValue": {
      "light": "red-600@10",
      "dark": "red-900@10"
    },
    "utilities": [
      "bg-destructive-10"
    ],
    "light": {
      "ref": "red-600",
      "alpha": 10,
      "hex": "#d241421a"
    },
    "dark": {
      "ref": "red-500",
      "alpha": 10,
      "hex": "#ee5c5a1a"
    },
    "description": "Translucent destructive surface (10%)."
  },
  {
    "name": "hover-destructive-20",
    "group": "Destructive",
    "cssVar": "--hover-destructive-20",
    "figma": "background/hover:destructive-20",
    "origin": "adjusted",
    "figmaValue": {
      "light": "red-600@20",
      "dark": "red-900@20"
    },
    "utilities": [
      "bg-hover-destructive-20",
      "text-hover-destructive-20",
      "border-hover-destructive-20"
    ],
    "light": {
      "ref": "red-600",
      "alpha": 20,
      "hex": "#d2414233"
    },
    "dark": {
      "ref": "red-500",
      "alpha": 20,
      "hex": "#ee5c5a33"
    },
    "description": "Translucent destructive surface on hover (20%)."
  },
  {
    "name": "success",
    "group": "Success",
    "cssVar": "--success",
    "figma": "background/success",
    "utilities": [
      "bg-success",
      "text-success",
      "border-success"
    ],
    "light": {
      "ref": "green-600",
      "hex": "#2d915e"
    },
    "dark": {
      "ref": "green-400",
      "hex": "#6cc290"
    },
    "description": "Positive state."
  },
  {
    "name": "success-foreground",
    "group": "Success",
    "cssVar": "--success-foreground",
    "figma": "foreground/success",
    "utilities": [
      "bg-success-foreground",
      "text-success-foreground",
      "border-success-foreground"
    ],
    "light": {
      "ref": "green-50",
      "hex": "#e7fbee"
    },
    "dark": {
      "ref": "green-950",
      "hex": "#02321b"
    },
    "description": "Text and icons on success."
  },
  {
    "name": "hover-success",
    "group": "Success",
    "cssVar": "--hover-success",
    "figma": "background/hover:succes",
    "utilities": [
      "bg-hover-success",
      "text-hover-success",
      "border-hover-success"
    ],
    "light": {
      "ref": "green-700",
      "hex": "#13794a"
    },
    "dark": {
      "ref": "green-500",
      "hex": "#49aa75"
    },
    "description": "Success background on hover. (Figma variable is spelled \"hover:succes\".)"
  },
  {
    "name": "success-muted",
    "group": "Success",
    "cssVar": "--success-muted",
    "figma": "background/success-muted",
    "utilities": [
      "bg-success-muted",
      "text-success-muted",
      "border-success-muted"
    ],
    "light": {
      "ref": "green-100",
      "hex": "#dcf4e4"
    },
    "dark": {
      "ref": "green-950",
      "hex": "#02321b"
    },
    "description": "Subtle success surface."
  },
  {
    "name": "success-muted-foreground",
    "group": "Success",
    "cssVar": "--success-muted-foreground",
    "figma": "foreground/success-muted",
    "utilities": [
      "bg-success-muted-foreground",
      "text-success-muted-foreground",
      "border-success-muted-foreground"
    ],
    "light": {
      "ref": "green-950",
      "hex": "#02321b"
    },
    "dark": {
      "ref": "green-50",
      "hex": "#e7fbee"
    },
    "description": "Text on the subtle success surface."
  },
  {
    "name": "warning",
    "group": "Warning",
    "cssVar": "--warning",
    "figma": "background/warning",
    "utilities": [
      "bg-warning",
      "text-warning",
      "border-warning"
    ],
    "light": {
      "ref": "yellow-400",
      "hex": "#bdb118"
    },
    "dark": {
      "ref": "yellow-200",
      "hex": "#f4e409"
    },
    "description": "Warning state."
  },
  {
    "name": "warning-foreground",
    "group": "Warning",
    "cssVar": "--warning-foreground",
    "figma": "foreground/warning",
    "utilities": [
      "bg-warning-foreground",
      "text-warning-foreground",
      "border-warning-foreground"
    ],
    "light": {
      "ref": "yellow-50",
      "hex": "#fdfbd7"
    },
    "dark": {
      "ref": "yellow-950",
      "hex": "#302c07"
    },
    "description": "Text and icons on warning."
  },
  {
    "name": "warning-muted",
    "group": "Warning",
    "cssVar": "--warning-muted",
    "figma": "background/warning-muted",
    "utilities": [
      "bg-warning-muted",
      "text-warning-muted",
      "border-warning-muted"
    ],
    "light": {
      "ref": "yellow-100",
      "hex": "#f6f2af"
    },
    "dark": {
      "ref": "yellow-800",
      "hex": "#565005"
    },
    "description": "Subtle warning surface."
  },
  {
    "name": "warning-muted-foreground",
    "group": "Warning",
    "cssVar": "--warning-muted-foreground",
    "figma": "foreground/warning-muted",
    "utilities": [
      "bg-warning-muted-foreground",
      "text-warning-muted-foreground",
      "border-warning-muted-foreground"
    ],
    "light": {
      "ref": "yellow-950",
      "hex": "#302c07"
    },
    "dark": {
      "ref": "yellow-100",
      "hex": "#f6f2af"
    },
    "description": "Text on the subtle warning surface."
  },
  {
    "name": "descriptive-lime",
    "group": "Descriptive",
    "cssVar": "--descriptive-lime",
    "figma": "background/descriptive-lime",
    "utilities": [
      "bg-descriptive-lime",
      "text-descriptive-lime",
      "border-descriptive-lime"
    ],
    "light": {
      "ref": "lime-50",
      "hex": "#eeffca"
    },
    "dark": {
      "ref": "lime-900",
      "hex": "#334103"
    },
    "description": "Lime tag / highlight surface."
  },
  {
    "name": "descriptive-lime-foreground",
    "group": "Descriptive",
    "cssVar": "--descriptive-lime-foreground",
    "figma": "foreground/descriptive-lime",
    "utilities": [
      "bg-descriptive-lime-foreground",
      "text-descriptive-lime-foreground",
      "border-descriptive-lime-foreground"
    ],
    "light": {
      "ref": "lime-950",
      "hex": "#212b01"
    },
    "dark": {
      "ref": "lime-50",
      "hex": "#eeffca"
    },
    "description": "Text on descriptive-lime."
  },
  {
    "name": "descriptive-blue",
    "group": "Descriptive",
    "cssVar": "--descriptive-blue",
    "figma": "background/descriptive-blue",
    "utilities": [
      "bg-descriptive-blue",
      "text-descriptive-blue",
      "border-descriptive-blue"
    ],
    "light": {
      "ref": "blue-100",
      "hex": "#e4edfe"
    },
    "dark": {
      "ref": "blue-950",
      "hex": "#021072"
    },
    "description": "Blue tag / highlight surface."
  },
  {
    "name": "descriptive-blue-foreground",
    "group": "Descriptive",
    "cssVar": "--descriptive-blue-foreground",
    "figma": "foreground/descriptive-blue",
    "utilities": [
      "bg-descriptive-blue-foreground",
      "text-descriptive-blue-foreground",
      "border-descriptive-blue-foreground"
    ],
    "light": {
      "ref": "blue-950",
      "hex": "#021072"
    },
    "dark": {
      "ref": "blue-100",
      "hex": "#e4edfe"
    },
    "description": "Text on descriptive-blue."
  },
  {
    "name": "descriptive-lime-brand",
    "group": "Descriptive",
    "cssVar": "--descriptive-lime-brand",
    "figma": "background/descriptive-lime-brand",
    "utilities": [
      "bg-descriptive-lime-brand",
      "text-descriptive-lime-brand",
      "border-descriptive-lime-brand"
    ],
    "light": {
      "ref": "lime-200",
      "hex": "#c5ef21"
    },
    "dark": {
      "ref": "lime-100",
      "hex": "#d2ff28"
    },
    "description": "Brand lime surface."
  },
  {
    "name": "descriptive-lime-brand-foreground",
    "group": "Descriptive",
    "cssVar": "--descriptive-lime-brand-foreground",
    "figma": "foreground/descriptive-lime-brand",
    "utilities": [
      "bg-descriptive-lime-brand-foreground",
      "text-descriptive-lime-brand-foreground",
      "border-descriptive-lime-brand-foreground"
    ],
    "light": {
      "ref": "lime-950",
      "hex": "#212b01"
    },
    "dark": {
      "ref": "lime-950",
      "hex": "#212b01"
    },
    "description": "Text on descriptive-lime-brand."
  },
  {
    "name": "descriptive-blue-brand",
    "group": "Descriptive",
    "cssVar": "--descriptive-blue-brand",
    "figma": "background/descriptive-blue-brand",
    "utilities": [
      "bg-descriptive-blue-brand",
      "text-descriptive-blue-brand",
      "border-descriptive-blue-brand"
    ],
    "light": {
      "ref": "blue-800",
      "hex": "#072ac8"
    },
    "dark": {
      "ref": "blue-600",
      "hex": "#376cfb"
    },
    "description": "Brand blue surface."
  },
  {
    "name": "descriptive-blue-brand-foreground",
    "group": "Descriptive",
    "cssVar": "--descriptive-blue-brand-foreground",
    "figma": "foreground/descriptive-blue-brand",
    "utilities": [
      "bg-descriptive-blue-brand-foreground",
      "text-descriptive-blue-brand-foreground",
      "border-descriptive-blue-brand-foreground"
    ],
    "light": {
      "ref": "blue-50",
      "hex": "#f4f8ff"
    },
    "dark": {
      "ref": "blue-50",
      "hex": "#f4f8ff"
    },
    "description": "Text on descriptive-blue-brand."
  },
  {
    "name": "descriptive-orange-brand",
    "group": "Descriptive",
    "cssVar": "--descriptive-orange-brand",
    "figma": "background/descriptive-orange-brand",
    "utilities": [
      "bg-descriptive-orange-brand",
      "text-descriptive-orange-brand",
      "border-descriptive-orange-brand"
    ],
    "light": {
      "ref": "orange-500",
      "hex": "#ff5900"
    },
    "dark": {
      "ref": "orange-400",
      "hex": "#fd8a62"
    },
    "description": "Brand orange surface (e.g. the logo tile)."
  },
  {
    "name": "descriptive-orange-brand-foreground",
    "group": "Descriptive",
    "cssVar": "--descriptive-orange-brand-foreground",
    "figma": "foreground/descriptive-orange-brand",
    "utilities": [
      "bg-descriptive-orange-brand-foreground",
      "text-descriptive-orange-brand-foreground",
      "border-descriptive-orange-brand-foreground"
    ],
    "light": {
      "ref": "orange-50",
      "hex": "#fff2ee"
    },
    "dark": {
      "ref": "orange-950",
      "hex": "#4e1601"
    },
    "description": "Text on descriptive-orange-brand."
  },
  {
    "name": "border",
    "group": "Borders & focus",
    "cssVar": "--border",
    "figma": "border/border",
    "utilities": [
      "bg-border",
      "text-border",
      "border-border"
    ],
    "light": {
      "ref": "gray-200",
      "hex": "#e0dedc"
    },
    "dark": {
      "ref": "gray-900",
      "hex": "#32302e"
    },
    "description": "Default border color."
  },
  {
    "name": "border-muted-40",
    "group": "Borders & focus",
    "cssVar": "--border-muted-40",
    "figma": "border/border-muted-40",
    "utilities": [
      "border-muted-40"
    ],
    "light": {
      "ref": "gray-600",
      "alpha": 40,
      "hex": "#7f7d7b66"
    },
    "dark": {
      "ref": "gray-400",
      "alpha": 40,
      "hex": "#b7b5b366"
    },
    "description": "Muted border, e.g. toast action buttons."
  },
  {
    "name": "border-destructive-50",
    "group": "Borders & focus",
    "cssVar": "--border-destructive-50",
    "figma": "border/border-destructive-50",
    "origin": "adjusted",
    "figmaValue": {
      "light": "red-200",
      "dark": "red-900"
    },
    "utilities": [
      "border-destructive-50"
    ],
    "light": {
      "ref": "red-600",
      "alpha": 50,
      "hex": "#d2414280"
    },
    "dark": {
      "ref": "red-900",
      "alpha": 50,
      "hex": "#71091380"
    },
    "description": "Outline of destructive elements such as buttons or alerts. The name announces the 50% opacity the Figma value was missing."
  },
  {
    "name": "input",
    "group": "Borders & focus",
    "cssVar": "--input",
    "figma": "background/input",
    "utilities": [
      "bg-input",
      "text-input",
      "border-input"
    ],
    "light": {
      "ref": "gray-200",
      "hex": "#e0dedc"
    },
    "dark": {
      "ref": "gray-900",
      "hex": "#32302e"
    },
    "description": "Border color of inputs such as <Input />, <Select />, <Textarea />."
  },
  {
    "name": "ring",
    "group": "Borders & focus",
    "cssVar": "--ring",
    "figma": "border/ring",
    "utilities": [
      "bg-ring",
      "text-ring",
      "border-ring"
    ],
    "light": {
      "ref": "gray-200",
      "hex": "#e0dedc"
    },
    "dark": {
      "ref": "gray-800",
      "hex": "#494745"
    },
    "description": "Focus ring color (Figma code syntax: --focus)."
  },
  {
    "name": "sidebar-background",
    "group": "Sidebar",
    "cssVar": "--sidebar-background",
    "figma": "sidebar/background/main",
    "utilities": [
      "bg-sidebar-background",
      "text-sidebar-background",
      "border-sidebar-background",
      "bg-sidebar"
    ],
    "light": {
      "ref": "gray-50",
      "hex": "#f4f2f0"
    },
    "dark": {
      "ref": "gray-950",
      "hex": "#1c1b1a"
    },
    "description": "Sidebar background."
  },
  {
    "name": "sidebar-foreground",
    "group": "Sidebar",
    "cssVar": "--sidebar-foreground",
    "figma": "sidebar/foreground/main",
    "utilities": [
      "bg-sidebar-foreground",
      "text-sidebar-foreground",
      "border-sidebar-foreground"
    ],
    "light": {
      "ref": "base-black",
      "hex": "#110f0e"
    },
    "dark": {
      "ref": "base-white",
      "hex": "#fbfaf9"
    },
    "description": "Sidebar text and icons."
  },
  {
    "name": "sidebar-foreground-70",
    "group": "Sidebar",
    "cssVar": "--sidebar-foreground-70",
    "figma": "sidebar/foreground/foreground-70",
    "utilities": [
      "bg-sidebar-foreground-70",
      "text-sidebar-foreground-70",
      "border-sidebar-foreground-70"
    ],
    "light": {
      "ref": "base-black",
      "alpha": 70,
      "hex": "#110f0eb3"
    },
    "dark": {
      "ref": "base-white",
      "alpha": 70,
      "hex": "#fbfaf9b3"
    },
    "description": "Secondary symbols in the sidebar (group labels)."
  },
  {
    "name": "sidebar-primary",
    "group": "Sidebar",
    "cssVar": "--sidebar-primary",
    "figma": null,
    "origin": "added",
    "utilities": [
      "bg-sidebar-primary",
      "text-sidebar-primary",
      "border-sidebar-primary"
    ],
    "light": {
      "ref": "base-black",
      "hex": "#110f0e"
    },
    "dark": {
      "ref": "base-white",
      "hex": "#fbfaf9"
    },
    "description": "Sidebar primary surface (same values as primary)."
  },
  {
    "name": "sidebar-primary-foreground",
    "group": "Sidebar",
    "cssVar": "--sidebar-primary-foreground",
    "figma": null,
    "origin": "added",
    "utilities": [
      "bg-sidebar-primary-foreground",
      "text-sidebar-primary-foreground",
      "border-sidebar-primary-foreground"
    ],
    "light": {
      "ref": "base-white",
      "hex": "#fbfaf9"
    },
    "dark": {
      "ref": "base-black",
      "hex": "#110f0e"
    },
    "description": "Text and icons on sidebar-primary (same values as primary-foreground)."
  },
  {
    "name": "sidebar-accent",
    "group": "Sidebar",
    "cssVar": "--sidebar-accent",
    "figma": "sidebar/background/accent",
    "utilities": [
      "bg-sidebar-accent",
      "text-sidebar-accent",
      "border-sidebar-accent"
    ],
    "light": {
      "ref": "orange-100",
      "hex": "#fee7df"
    },
    "dark": {
      "ref": "orange-950",
      "hex": "#4e1601"
    },
    "description": "Sidebar hover and active surfaces."
  },
  {
    "name": "sidebar-accent-foreground",
    "group": "Sidebar",
    "cssVar": "--sidebar-accent-foreground",
    "figma": "sidebar/foreground/accent",
    "utilities": [
      "bg-sidebar-accent-foreground",
      "text-sidebar-accent-foreground",
      "border-sidebar-accent-foreground"
    ],
    "light": {
      "ref": "orange-950",
      "hex": "#4e1601"
    },
    "dark": {
      "ref": "orange-100",
      "hex": "#fee7df"
    },
    "description": "Text and icons on sidebar-accent."
  },
  {
    "name": "sidebar-border",
    "group": "Sidebar",
    "cssVar": "--sidebar-border",
    "figma": "sidebar/border/border/border",
    "utilities": [
      "bg-sidebar-border",
      "text-sidebar-border",
      "border-sidebar-border"
    ],
    "light": {
      "ref": "gray-100",
      "hex": "#efedeb"
    },
    "dark": {
      "ref": "gray-900",
      "hex": "#32302e"
    },
    "description": "Sidebar borders."
  },
  {
    "name": "sidebar-ring",
    "group": "Sidebar",
    "cssVar": "--sidebar-ring",
    "figma": "sidebar/border/border/ring",
    "utilities": [
      "bg-sidebar-ring",
      "text-sidebar-ring",
      "border-sidebar-ring"
    ],
    "light": {
      "ref": "gray-200",
      "hex": "#e0dedc"
    },
    "dark": {
      "ref": "gray-800",
      "hex": "#494745"
    },
    "description": "Sidebar focus ring."
  },
  {
    "name": "chart-1",
    "group": "Chart",
    "cssVar": "--chart-1",
    "figma": null,
    "origin": "proposed",
    "utilities": [
      "bg-chart-1",
      "text-chart-1",
      "border-chart-1"
    ],
    "light": {
      "ref": "orange-500",
      "hex": "#ff5900"
    },
    "dark": {
      "ref": "orange-600",
      "hex": "#d24b0d"
    },
    "description": "Chart series 1."
  },
  {
    "name": "chart-2",
    "group": "Chart",
    "cssVar": "--chart-2",
    "figma": null,
    "origin": "proposed",
    "utilities": [
      "bg-chart-2",
      "text-chart-2",
      "border-chart-2"
    ],
    "light": {
      "ref": "green-800",
      "hex": "#07623a"
    },
    "dark": {
      "ref": "green-500",
      "hex": "#49aa75"
    },
    "description": "Chart series 2."
  },
  {
    "name": "chart-3",
    "group": "Chart",
    "cssVar": "--chart-3",
    "figma": null,
    "origin": "proposed",
    "utilities": [
      "bg-chart-3",
      "text-chart-3",
      "border-chart-3"
    ],
    "light": {
      "ref": "yellow-600",
      "hex": "#887f0e"
    },
    "dark": {
      "ref": "yellow-700",
      "hex": "#6f6709"
    },
    "description": "Chart series 3."
  },
  {
    "name": "chart-4",
    "group": "Chart",
    "cssVar": "--chart-4",
    "figma": null,
    "origin": "proposed",
    "utilities": [
      "bg-chart-4",
      "text-chart-4",
      "border-chart-4"
    ],
    "light": {
      "ref": "blue-500",
      "hex": "#5e8dfc"
    },
    "dark": {
      "ref": "blue-500",
      "hex": "#5e8dfc"
    },
    "description": "Chart series 4."
  },
  {
    "name": "chart-5",
    "group": "Chart",
    "cssVar": "--chart-5",
    "figma": null,
    "origin": "proposed",
    "utilities": [
      "bg-chart-5",
      "text-chart-5",
      "border-chart-5"
    ],
    "light": {
      "ref": "lime-600",
      "hex": "#6e880e"
    },
    "dark": {
      "ref": "lime-500",
      "hex": "#84a213"
    },
    "description": "Chart series 5."
  }
]

export type TextStyle = {
  /** Figma text style name, e.g. "text-sm/leading-5/medium". */
  name: string
  font: "sans"
  /** Weight used in Figma. */
  weight: number
  /** Font size in px. */
  size: number
  /** Line height in px, or "100%" for leading-none. */
  lineHeight: number | "100%"
  /** Figma letter spacing, e.g. "-2.5%" or "-0.6px". */
  letterSpacing: string
  decoration?: "underline"
  case?: "uppercase"
  /** Tailwind classes that reproduce the style. */
  classes: string
}

export const fonts = {
  "sans": {
    "family": "Aspekta",
    "weights": [
      400,
      500,
      600,
      700,
      800
    ]
  }
} as const

export const textStyles: TextStyle[] = [
  {
    "name": "text-9xl/leading-none/normal",
    "font": "sans",
    "weight": 400,
    "size": 128,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-9xl leading-none font-normal tracking-tight"
  },
  {
    "name": "text-9xl/leading-none/medium",
    "font": "sans",
    "weight": 500,
    "size": 128,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-9xl leading-none font-medium tracking-tight"
  },
  {
    "name": "text-9xl/leading-none/semibold",
    "font": "sans",
    "weight": 600,
    "size": 128,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-9xl leading-none font-semibold tracking-tight"
  },
  {
    "name": "text-9xl/leading-none/bold",
    "font": "sans",
    "weight": 700,
    "size": 128,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-9xl leading-none font-bold tracking-tight"
  },
  {
    "name": "text-9xl/leading-none/extrabold",
    "font": "sans",
    "weight": 800,
    "size": 128,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-9xl leading-none font-extrabold tracking-tight"
  },
  {
    "name": "text-8xl/leading-none/normal",
    "font": "sans",
    "weight": 400,
    "size": 96,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-8xl leading-none font-normal tracking-tight"
  },
  {
    "name": "text-8xl/leading-none/medium",
    "font": "sans",
    "weight": 500,
    "size": 96,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-8xl leading-none font-medium tracking-tight"
  },
  {
    "name": "text-8xl/leading-none/semibold",
    "font": "sans",
    "weight": 600,
    "size": 96,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-8xl leading-none font-semibold tracking-tight"
  },
  {
    "name": "text-8xl/leading-none/bold",
    "font": "sans",
    "weight": 700,
    "size": 96,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-8xl leading-none font-bold tracking-tight"
  },
  {
    "name": "text-8xl/leading-none/extrabold",
    "font": "sans",
    "weight": 800,
    "size": 96,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-8xl leading-none font-extrabold tracking-tight"
  },
  {
    "name": "text-7xl/leading-none/normal",
    "font": "sans",
    "weight": 400,
    "size": 72,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-7xl leading-none font-normal tracking-tight"
  },
  {
    "name": "text-7xl/leading-none/medium",
    "font": "sans",
    "weight": 500,
    "size": 72,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-7xl leading-none font-medium tracking-tight"
  },
  {
    "name": "text-7xl/leading-none/semibold",
    "font": "sans",
    "weight": 600,
    "size": 72,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-7xl leading-none font-semibold tracking-tight"
  },
  {
    "name": "text-7xl/leading-none/bold",
    "font": "sans",
    "weight": 700,
    "size": 72,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-7xl leading-none font-bold tracking-tight"
  },
  {
    "name": "text-7xl/leading-none/extrabold",
    "font": "sans",
    "weight": 800,
    "size": 72,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-7xl leading-none font-extrabold tracking-tight"
  },
  {
    "name": "text-6xl/leading-none/normal",
    "font": "sans",
    "weight": 400,
    "size": 60,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-6xl leading-none font-normal tracking-tight"
  },
  {
    "name": "text-6xl/leading-none/medium",
    "font": "sans",
    "weight": 500,
    "size": 60,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-6xl leading-none font-medium tracking-tight"
  },
  {
    "name": "text-6xl/leading-none/semibold",
    "font": "sans",
    "weight": 600,
    "size": 60,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-6xl leading-none font-semibold tracking-tight"
  },
  {
    "name": "text-6xl/leading-none/bold",
    "font": "sans",
    "weight": 700,
    "size": 60,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-6xl leading-none font-bold tracking-tight"
  },
  {
    "name": "text-6xl/leading-none/extrabold",
    "font": "sans",
    "weight": 800,
    "size": 60,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-6xl leading-none font-extrabold tracking-tight"
  },
  {
    "name": "text-5xl/leading-none/normal",
    "font": "sans",
    "weight": 400,
    "size": 48,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-5xl leading-none font-normal tracking-tight"
  },
  {
    "name": "text-5xl/leading-none/medium",
    "font": "sans",
    "weight": 500,
    "size": 48,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-5xl leading-none font-medium tracking-tight"
  },
  {
    "name": "text-5xl/leading-none/semibold",
    "font": "sans",
    "weight": 600,
    "size": 48,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-5xl leading-none font-semibold tracking-tight"
  },
  {
    "name": "text-5xl/leading-none/bold",
    "font": "sans",
    "weight": 700,
    "size": 48,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-5xl leading-none font-bold tracking-tight"
  },
  {
    "name": "text-5xl/leading-none/extrabold",
    "font": "sans",
    "weight": 800,
    "size": 48,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-5xl leading-none font-extrabold tracking-tight"
  },
  {
    "name": "text-4xl/leading-10/normal",
    "font": "sans",
    "weight": 400,
    "size": 36,
    "lineHeight": 40,
    "letterSpacing": "-2.5%",
    "classes": "text-4xl leading-10 font-normal tracking-tight"
  },
  {
    "name": "text-4xl/leading-10/medium",
    "font": "sans",
    "weight": 500,
    "size": 36,
    "lineHeight": 40,
    "letterSpacing": "-2.5%",
    "classes": "text-4xl leading-10 font-medium tracking-tight"
  },
  {
    "name": "text-4xl/leading-10/semibold",
    "font": "sans",
    "weight": 600,
    "size": 36,
    "lineHeight": 40,
    "letterSpacing": "-2.5%",
    "classes": "text-4xl leading-10 font-semibold tracking-tight"
  },
  {
    "name": "text-4xl/leading-10/bold",
    "font": "sans",
    "weight": 700,
    "size": 36,
    "lineHeight": 40,
    "letterSpacing": "-2.5%",
    "classes": "text-4xl leading-10 font-bold tracking-tight"
  },
  {
    "name": "text-4xl/leading-none/normal",
    "font": "sans",
    "weight": 400,
    "size": 36,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-4xl leading-none font-normal tracking-tight"
  },
  {
    "name": "text-4xl/leading-none/medium",
    "font": "sans",
    "weight": 500,
    "size": 36,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-4xl leading-none font-medium tracking-tight"
  },
  {
    "name": "text-4xl/leading-none/semibold",
    "font": "sans",
    "weight": 600,
    "size": 36,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-4xl leading-none font-semibold tracking-tight"
  },
  {
    "name": "text-4xl/leading-none/bold",
    "font": "sans",
    "weight": 700,
    "size": 36,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-4xl leading-none font-bold tracking-tight"
  },
  {
    "name": "text-3xl/leading-9/normal",
    "font": "sans",
    "weight": 400,
    "size": 30,
    "lineHeight": 36,
    "letterSpacing": "-0.75px",
    "classes": "text-3xl leading-9 font-normal tracking-tight"
  },
  {
    "name": "text-3xl/leading-9/medium",
    "font": "sans",
    "weight": 500,
    "size": 30,
    "lineHeight": 36,
    "letterSpacing": "-2.5%",
    "classes": "text-3xl leading-9 font-medium tracking-tight"
  },
  {
    "name": "text-3xl/leading-9/semibold",
    "font": "sans",
    "weight": 600,
    "size": 30,
    "lineHeight": 36,
    "letterSpacing": "-2.5%",
    "classes": "text-3xl leading-9 font-semibold tracking-tight"
  },
  {
    "name": "text-3xl/leading-9/bold",
    "font": "sans",
    "weight": 700,
    "size": 30,
    "lineHeight": 36,
    "letterSpacing": "-2.5%",
    "classes": "text-3xl leading-9 font-bold tracking-tight"
  },
  {
    "name": "text-3xl/leading-none/normal",
    "font": "sans",
    "weight": 400,
    "size": 30,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-3xl leading-none font-normal tracking-tight"
  },
  {
    "name": "text-3xl/leading-none/medium",
    "font": "sans",
    "weight": 500,
    "size": 30,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-3xl leading-none font-medium tracking-tight"
  },
  {
    "name": "text-3xl/leading-none/semibold",
    "font": "sans",
    "weight": 600,
    "size": 30,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-3xl leading-none font-semibold tracking-tight"
  },
  {
    "name": "text-3xl/leading-none/bold",
    "font": "sans",
    "weight": 700,
    "size": 30,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-3xl leading-none font-bold tracking-tight"
  },
  {
    "name": "text-2xl/leading-8/normal",
    "font": "sans",
    "weight": 400,
    "size": 24,
    "lineHeight": 32,
    "letterSpacing": "-0.6px",
    "classes": "text-2xl leading-8 font-normal tracking-tight"
  },
  {
    "name": "text-2xl/leading-8/medium",
    "font": "sans",
    "weight": 500,
    "size": 24,
    "lineHeight": 32,
    "letterSpacing": "-0.6px",
    "classes": "text-2xl leading-8 font-medium tracking-tight"
  },
  {
    "name": "text-2xl/leading-8/semibold",
    "font": "sans",
    "weight": 600,
    "size": 24,
    "lineHeight": 32,
    "letterSpacing": "-0.6px",
    "classes": "text-2xl leading-8 font-semibold tracking-tight"
  },
  {
    "name": "text-2xl/leading-8/bold",
    "font": "sans",
    "weight": 700,
    "size": 24,
    "lineHeight": 32,
    "letterSpacing": "-0.6px",
    "classes": "text-2xl leading-8 font-bold tracking-tight"
  },
  {
    "name": "text-2xl/leading-none/normal",
    "font": "sans",
    "weight": 400,
    "size": 24,
    "lineHeight": "100%",
    "letterSpacing": "-0.6px",
    "classes": "text-2xl leading-none font-normal tracking-tight"
  },
  {
    "name": "text-2xl/leading-none/medium",
    "font": "sans",
    "weight": 500,
    "size": 24,
    "lineHeight": "100%",
    "letterSpacing": "-0.6px",
    "classes": "text-2xl leading-none font-medium tracking-tight"
  },
  {
    "name": "text-2xl/leading-none/semibold",
    "font": "sans",
    "weight": 600,
    "size": 24,
    "lineHeight": "100%",
    "letterSpacing": "-0.6px",
    "classes": "text-2xl leading-none font-semibold tracking-tight"
  },
  {
    "name": "text-2xl/leading-none/bold",
    "font": "sans",
    "weight": 700,
    "size": 24,
    "lineHeight": "100%",
    "letterSpacing": "-0.6px",
    "classes": "text-2xl leading-none font-bold tracking-tight"
  },
  {
    "name": "text-xl/leading-7/normal",
    "font": "sans",
    "weight": 400,
    "size": 20,
    "lineHeight": 28,
    "letterSpacing": "-0.6px",
    "classes": "text-xl leading-7 font-normal tracking-[-0.6px]"
  },
  {
    "name": "text-xl/leading-7/medium",
    "font": "sans",
    "weight": 500,
    "size": 20,
    "lineHeight": 28,
    "letterSpacing": "-0.6px",
    "classes": "text-xl leading-7 font-medium tracking-[-0.6px]"
  },
  {
    "name": "text-xl/leading-7/semibold",
    "font": "sans",
    "weight": 600,
    "size": 20,
    "lineHeight": 28,
    "letterSpacing": "-0.6px",
    "classes": "text-xl leading-7 font-semibold tracking-[-0.6px]"
  },
  {
    "name": "text-xl/leading-7/bold",
    "font": "sans",
    "weight": 700,
    "size": 20,
    "lineHeight": 28,
    "letterSpacing": "-0.6px",
    "classes": "text-xl leading-7 font-bold tracking-[-0.6px]"
  },
  {
    "name": "text-xl/leading-none/normal",
    "font": "sans",
    "weight": 400,
    "size": 20,
    "lineHeight": "100%",
    "letterSpacing": "-0.6px",
    "classes": "text-xl leading-none font-normal tracking-[-0.6px]"
  },
  {
    "name": "text-xl/leading-none/medium",
    "font": "sans",
    "weight": 500,
    "size": 20,
    "lineHeight": "100%",
    "letterSpacing": "-0.6px",
    "classes": "text-xl leading-none font-medium tracking-[-0.6px]"
  },
  {
    "name": "text-xl/leading-none/semibold",
    "font": "sans",
    "weight": 600,
    "size": 20,
    "lineHeight": "100%",
    "letterSpacing": "-0.6px",
    "classes": "text-xl leading-none font-semibold tracking-[-0.6px]"
  },
  {
    "name": "text-xl/leading-none/bold",
    "font": "sans",
    "weight": 700,
    "size": 20,
    "lineHeight": "100%",
    "letterSpacing": "-0.6px",
    "classes": "text-xl leading-none font-bold tracking-[-0.6px]"
  },
  {
    "name": "text-lg/leading-7/normal",
    "font": "sans",
    "weight": 400,
    "size": 18,
    "lineHeight": 28,
    "letterSpacing": "0",
    "classes": "text-lg leading-7 font-normal"
  },
  {
    "name": "text-lg/leading-7/medium",
    "font": "sans",
    "weight": 500,
    "size": 18,
    "lineHeight": 28,
    "letterSpacing": "0",
    "classes": "text-lg leading-7 font-medium"
  },
  {
    "name": "text-lg/leading-7/semibold",
    "font": "sans",
    "weight": 600,
    "size": 18,
    "lineHeight": 28,
    "letterSpacing": "0",
    "classes": "text-lg leading-7 font-semibold"
  },
  {
    "name": "text-lg/leading-7/bold",
    "font": "sans",
    "weight": 700,
    "size": 18,
    "lineHeight": 28,
    "letterSpacing": "0",
    "classes": "text-lg leading-7 font-bold"
  },
  {
    "name": "text-lg/leading-none/normal",
    "font": "sans",
    "weight": 400,
    "size": 18,
    "lineHeight": "100%",
    "letterSpacing": "0",
    "classes": "text-lg leading-none font-normal"
  },
  {
    "name": "text-lg/leading-none/medium",
    "font": "sans",
    "weight": 500,
    "size": 18,
    "lineHeight": "100%",
    "letterSpacing": "0",
    "classes": "text-lg leading-none font-medium"
  },
  {
    "name": "text-lg/leading-none/semibold",
    "font": "sans",
    "weight": 600,
    "size": 18,
    "lineHeight": "100%",
    "letterSpacing": "-2.5%",
    "classes": "text-lg leading-none font-semibold tracking-tight"
  },
  {
    "name": "text-lg/leading-none/bold",
    "font": "sans",
    "weight": 700,
    "size": 18,
    "lineHeight": "100%",
    "letterSpacing": "0",
    "classes": "text-lg leading-none font-bold"
  },
  {
    "name": "text-base/leading-7/normal",
    "font": "sans",
    "weight": 400,
    "size": 16,
    "lineHeight": 28,
    "letterSpacing": "0",
    "classes": "text-base leading-7 font-normal"
  },
  {
    "name": "text-base/leading-7/medium",
    "font": "sans",
    "weight": 500,
    "size": 16,
    "lineHeight": 28,
    "letterSpacing": "0",
    "classes": "text-base leading-7 font-medium"
  },
  {
    "name": "text-base/leading-7/semibold",
    "font": "sans",
    "weight": 600,
    "size": 16,
    "lineHeight": 28,
    "letterSpacing": "0",
    "classes": "text-base leading-7 font-semibold"
  },
  {
    "name": "text-base/leading-7/bold",
    "font": "sans",
    "weight": 700,
    "size": 16,
    "lineHeight": 28,
    "letterSpacing": "0",
    "classes": "text-base leading-7 font-bold"
  },
  {
    "name": "text-base/leading-6/normal",
    "font": "sans",
    "weight": 400,
    "size": 16,
    "lineHeight": 24,
    "letterSpacing": "0",
    "classes": "text-base leading-6 font-normal"
  },
  {
    "name": "text-base/leading-6/medium",
    "font": "sans",
    "weight": 500,
    "size": 16,
    "lineHeight": 24,
    "letterSpacing": "0",
    "classes": "text-base leading-6 font-medium"
  },
  {
    "name": "text-base/leading-6/semibold",
    "font": "sans",
    "weight": 600,
    "size": 16,
    "lineHeight": 24,
    "letterSpacing": "0",
    "classes": "text-base leading-6 font-semibold"
  },
  {
    "name": "text-base/leading-6/bold",
    "font": "sans",
    "weight": 700,
    "size": 16,
    "lineHeight": 24,
    "letterSpacing": "0",
    "classes": "text-base leading-6 font-bold"
  },
  {
    "name": "text-base/leading-6/underline",
    "font": "sans",
    "weight": 400,
    "size": 16,
    "lineHeight": 24,
    "letterSpacing": "0",
    "decoration": "underline",
    "classes": "text-base leading-6 font-normal underline"
  },
  {
    "name": "text-base/leading-6/medium-underline",
    "font": "sans",
    "weight": 500,
    "size": 16,
    "lineHeight": 24,
    "letterSpacing": "0",
    "decoration": "underline",
    "classes": "text-base leading-6 font-medium underline"
  },
  {
    "name": "text-base/leading-none/normal",
    "font": "sans",
    "weight": 400,
    "size": 16,
    "lineHeight": "100%",
    "letterSpacing": "0",
    "classes": "text-base leading-none font-normal"
  },
  {
    "name": "text-base/leading-none/medium",
    "font": "sans",
    "weight": 500,
    "size": 16,
    "lineHeight": "100%",
    "letterSpacing": "0",
    "classes": "text-base leading-none font-medium"
  },
  {
    "name": "text-base/leading-none/semibold",
    "font": "sans",
    "weight": 600,
    "size": 16,
    "lineHeight": "100%",
    "letterSpacing": "0",
    "classes": "text-base leading-none font-semibold"
  },
  {
    "name": "text-base/leading-none/bold",
    "font": "sans",
    "weight": 700,
    "size": 16,
    "lineHeight": "100%",
    "letterSpacing": "0",
    "classes": "text-base leading-none font-bold"
  },
  {
    "name": "text-base/leading-none/underline",
    "font": "sans",
    "weight": 400,
    "size": 16,
    "lineHeight": "100%",
    "letterSpacing": "0",
    "decoration": "underline",
    "classes": "text-base leading-none font-normal underline"
  },
  {
    "name": "text-base/leading-none/medium-undeline",
    "font": "sans",
    "weight": 500,
    "size": 16,
    "lineHeight": "100%",
    "letterSpacing": "0",
    "decoration": "underline",
    "classes": "text-base leading-none font-medium underline"
  },
  {
    "name": "text-sm/leading-6/normal",
    "font": "sans",
    "weight": 400,
    "size": 14,
    "lineHeight": 24,
    "letterSpacing": "0",
    "classes": "text-sm leading-6 font-normal"
  },
  {
    "name": "text-sm/leading-6/medium",
    "font": "sans",
    "weight": 500,
    "size": 14,
    "lineHeight": 24,
    "letterSpacing": "0",
    "classes": "text-sm leading-6 font-medium"
  },
  {
    "name": "text-sm/leading-6/semibold",
    "font": "sans",
    "weight": 600,
    "size": 14,
    "lineHeight": 24,
    "letterSpacing": "0",
    "classes": "text-sm leading-6 font-semibold"
  },
  {
    "name": "text-sm/leading-6/bold",
    "font": "sans",
    "weight": 700,
    "size": 14,
    "lineHeight": 24,
    "letterSpacing": "0",
    "classes": "text-sm leading-6 font-bold"
  },
  {
    "name": "text-sm/leading-6/medium-underline",
    "font": "sans",
    "weight": 500,
    "size": 14,
    "lineHeight": 24,
    "letterSpacing": "0",
    "decoration": "underline",
    "classes": "text-sm leading-6 font-medium underline"
  },
  {
    "name": "text-sm/leading-5/normal",
    "font": "sans",
    "weight": 400,
    "size": 14,
    "lineHeight": 20,
    "letterSpacing": "0",
    "classes": "text-sm leading-5 font-normal"
  },
  {
    "name": "text-sm/leading-5/medium",
    "font": "sans",
    "weight": 500,
    "size": 14,
    "lineHeight": 20,
    "letterSpacing": "0",
    "classes": "text-sm leading-5 font-medium"
  },
  {
    "name": "text-sm/leading-5/semibold",
    "font": "sans",
    "weight": 600,
    "size": 14,
    "lineHeight": 20,
    "letterSpacing": "0",
    "classes": "text-sm leading-5 font-semibold"
  },
  {
    "name": "text-sm/leading-5/bold",
    "font": "sans",
    "weight": 700,
    "size": 14,
    "lineHeight": 20,
    "letterSpacing": "0",
    "classes": "text-sm leading-5 font-bold"
  },
  {
    "name": "text-sm/leading-5/underline",
    "font": "sans",
    "weight": 400,
    "size": 14,
    "lineHeight": 20,
    "letterSpacing": "0",
    "decoration": "underline",
    "classes": "text-sm leading-5 font-normal underline"
  },
  {
    "name": "text-sm/leading-none/normal",
    "font": "sans",
    "weight": 400,
    "size": 14,
    "lineHeight": "100%",
    "letterSpacing": "0",
    "classes": "text-sm leading-none font-normal"
  },
  {
    "name": "text-sm/leading-none/medium",
    "font": "sans",
    "weight": 500,
    "size": 14,
    "lineHeight": "100%",
    "letterSpacing": "0",
    "classes": "text-sm leading-none font-medium"
  },
  {
    "name": "text-sm/leading-none/semibold",
    "font": "sans",
    "weight": 600,
    "size": 14,
    "lineHeight": "100%",
    "letterSpacing": "0",
    "classes": "text-sm leading-none font-semibold"
  },
  {
    "name": "text-sm/leading-none/bold",
    "font": "sans",
    "weight": 700,
    "size": 14,
    "lineHeight": "100%",
    "letterSpacing": "0",
    "classes": "text-sm leading-none font-bold"
  },
  {
    "name": "text-xs/leading-4/normal",
    "font": "sans",
    "weight": 400,
    "size": 12,
    "lineHeight": 16,
    "letterSpacing": "0",
    "classes": "text-xs leading-4 font-normal"
  },
  {
    "name": "text-xs/leading-4/medium",
    "font": "sans",
    "weight": 500,
    "size": 12,
    "lineHeight": 16,
    "letterSpacing": "0",
    "classes": "text-xs leading-4 font-medium"
  },
  {
    "name": "text-xs/leading-4/semibold",
    "font": "sans",
    "weight": 600,
    "size": 12,
    "lineHeight": 16,
    "letterSpacing": "0",
    "classes": "text-xs leading-4 font-semibold"
  },
  {
    "name": "text-xs/leading-4/bold",
    "font": "sans",
    "weight": 700,
    "size": 12,
    "lineHeight": 16,
    "letterSpacing": "0",
    "classes": "text-xs leading-4 font-bold"
  }
]
